### PR TITLE
Card View - added Org Chart panel

### PR DESCRIPTION
**Pull request by scudmarx**
Added Org Chart to Card View, to provide information about the list's structure, describing what units are joined to what other units.  Displaying this is controlled by an option in the menu, which defaults to off. Also adds option to this menu for controlling whether identical units are merged into one card or not (implementing #259 ), adds the Card/List toggle to the menu, and reflows the menu options.

OrgChart

Also corrects the unit merging logic which was sometimes allowing the display of multiple identical cards instead of merging them into a single card with a count (selectionId field was stripped but joinToUnit and 'id' fields were not - they now are).

Also: Special Rules box in Card View displays entries for e.g. 'Defense' where there are no rules text.  This fixes that, skipping rules with no description.

bad

good

### CODE REVIEW

**Comment by BaptisteD** [comment]
Why did you add the view mode in the settings panel when it's already present in the page ? 
I think this redundancy increase the perceived complexity.

Screenshot_20211214-151159


In the org chart, why some units have a loadout and some don't ? 
Screenshot_20211214-151147

**Comment by scudmarx** [comment]
> Why did you add the view mode in the settings panel when it's already present in the page ? I think this redundancy increase the perceived complexity.

Long story short - because while testing and using the page a bunch it seemed like it needed to have the option there. I don't think it increases the perceived complexity I think it makes sense having all of the display settings, especially that most significant display setting, together under the 'display settings' menu. If anything the toggle on the page outside the menu should go I think. The process went like this:

- Some of the menu items don't have any effect on List View (not just the new ones, some of the old settings only affect Card View too).  Having options in the list that you can toggle but which don't do anything definitely *is* counterintuitive, so...
- I disabled the options that don't do anything in List View while in List View. But now it can be a little confusing to see some options disabled, and the menu has no clear indication that 'Card View' and 'List View' even exist, let alone that they might be relevant to the options, so...
- I put the View Toggle right at the top of the list to show that it matters and is important.  Toggling it on and off shows the reason the options are disabled in a nice intuitive way.
 
> In the org chart, why some units have a loadout and some don't ? 

If you only list "Master Brother" linked to "Battle Brothers" and you have different units of Battle Brothers with different setups, it won't be clear which group the Master Brother is attached to, so the chart needs to differentiate between differently-equipped units. Every unit it lists has a summary of the options it has taken - the ones that don't show any extra information are units you haven't selected any upgrades for - they are the basic vanilla units.

**Comment by BaptisteD** [comment]
Alright, I dig the setting position. In this case it should be removed from the page (not having a duplicate for the same setting) and I would hide unavailable settings depending of the current view mode, rather than having them disabled. 

Okay, let's keep the org chart like that then. 
Thanks !

**Comment by scudmarx** [comment]
> In this case it should be removed from the page (not having a duplicate for the same setting) and I would hide unavailable settings depending of the current view mode, rather than having them disabled.

OK updated with both of these.  Thanks! :)

**Comment by BaptisteD** [comment]
Why is there separators in this menu ? 

Screenshot_20211214-233618

The catégories aren't obvious and I don't think that it's necessary (except maybe under the view mode at max)

If we really feel the need to structure this panel, we should use section titles instead. Like here

Screenshot_20211214-233805

**Comment by scudmarx** [comment]
I just found it visually a bit nicer to break the list up I guess? The categories made perfect sense to me - [modifies page behaviour] / [displays more data] / [shows extra sections], but the categorisation's not that important, it just seemed like a reasonable way to break the list up a bit. 🤷

**Pull request closed without merging**
