### PR TITLE
Files searchbox

### PR DESCRIPTION
**Pull request by scudmarx**
bro

### CODE REVIEW

**Comment by AdamLay** [comment]
Thanks for this!

@BaptisteD are you happy with how this looks?

**Comment by BaptisteD** [comment]
On mobile I would propose to have a search icon on the navbar, like in the exemple below. 

Screenshot_20211124-122652

Screenshot_20211124-122704

**Comment by BaptisteD** [comment]
On desktop it's a bit harder, right now it's a bit floating and unbalanced.

How much of a need is it to search army in army forge today ? With only the official armies, I'm not convinced.

**Comment by scudmarx** [comment]
> On desktop it's a bit harder, right now it's a bit floating and unbalanced.

Have moved it around to the menu bar as you suggested.

> How much of a need is it to search army in army forge today ? With only the official armies, I'm not convinced.

It's obviously a lot more useful in the list of all of the custom armies from the live WebCompanion. It's *very* useful there. And it's pretty nice to have on the shorter official-only list too I find.

**Comment by BaptisteD** [comment]
> It's obviously a lot more useful in the list of all of the custom armies from the live WebCompanion. It's very useful there. And it's pretty nice to have on the shorter official-only list too I find.

Yeah, that's why I wanted to wait until we have the custom lists. But we can do it in advance.


So, could you show the "search" word only after a tap on the search icon ? 
You can take a look at the rename unit feature. I would expect the same kind of behavior. 

Also, when the "search" word appears, it's not vertically centered

Capture d’écran 2021-11-24 à 22 16 20
.

**Comment by BaptisteD** [comment]
Well done ! 
The live filtering and the ability to search by user name is really neat !  👌

**Comment by AdamLay** [comment]
Agreed - looking good, thank you!

**Pull request merged**
