### PR TITLE
Added 'competitive' field to List data. 

### PR DESCRIPTION
**Pull request by scudmarx**
Dilemma

Competitive rules enforced accordingly.

SeemsABitMuchTBH

Some elements of competitive rules have been built into some of the core functionality - e.g. in non-competitive, units aren't restricted to having a single Hero attached, but displaying a configuration like that is not currently working nicely.

### CODE REVIEW

**Comment by scudmarx** [comment]
Have sorted out all of the Hero-joining shenanigans that are allowed under non-comp rules, but haven't yet re-implemented the comp rules against all of that as validation checks.

Vercel is saying it has failed to deploy but I can't see why - the 'details' link goes to a 404 for me.  It is all working on my dev build, perhaps one of your shiny new unit tests is failing or something. Probably to do with combine unit implementation, I reworked how the child/parent units are structured and this may be causing an incorrect assert? 🤷

**Comment by scudmarx** [comment]
OKFine

**Comment by BaptisteD** [comment]
Hey !
Just so you know, it was a request from OPA that the competitive rules check was always activated (probably because it's a more balanced way of playing). But that it should be a warning and not a limitation. 
That's why we have the notification system we have implemented. 

So I don't think that we should have the checkbox in the selection screen. It goes against OPA wishes.

**Comment by scudmarx** [comment]
Competitive option no longer list-wide, is just page state, and only controls 'joining' behaviour. 'Competitive Validation' errors will always appear regardless of its value.

**Pull request merged**
