### PR TITLE
Implemented Unit Duplication

### PR DESCRIPTION
**Pull request by scudmarx**
Screenshot 2021-11-17 122731

#149 linked

### CODE REVIEW

**Comment by BaptisteD** [comment]
Hey ! 
Thanks for the dev on this, that's a really expected feature ! 
Could you implement it like proposed in this issue plz ? 
https://github.com/AdamLay/opr-army-forge/issues/149

**Comment by scudmarx** [comment]
Now with added dropdowns, for all your "now where did I put that button" needs. 👍 

Screenshot 2021-11-18 111117

Currently no 'remove' option on the group header menu, only duplicate (since no group removal function currently implemented, shouldn't be hard though if wanna add it in the next sprint).

**Comment by BaptisteD** [comment]
Thanks !  :pray:

**Comment by AdamLay** [comment]
Ah I missed that the UI work had been done - great, thank you! :)

**Pull request merged**
