### PR TITLE
header of mainlist (showing list name and pts) now sticky

### PR DESCRIPTION
**Pull request by scudmarx**
Moved the header from the desktopview  component to the mainlist component where it can be combined as a stickyheader with the collapse-all button. Made this header sticky like the UnitSelection header.

stickyhead

### CODE REVIEW

**Comment by BaptisteD** [comment]
Can you activate a drop shadow for these headers when they're not at there start location ? (Once you scrolled in the list)

**Comment by scudmarx** [comment]
Implemented a drop-shadow. Only displaying this when scrolled is difficult though.

**Comment by scudmarx** [comment]
OK managed it. 👍

**Comment by BaptisteD** [comment]
Well done ! 
That's really nice !  

Do you plan to do something similar for the header in the Upgrade panel ? 
It works on mobile, the header is sticky, but not on desktop yet.

**Comment by scudmarx** [comment]
Sure, the Upgrades header is now sticky too. 👍

**Comment by scudmarx** [comment]
> Not sure that "Units" & the view mode really needs to stay in the header. It eats some display space without offering you any added value of the content you're scrolling through. Could you remove it from the headers and let them in the scroll view ?

OK this is done too.

**Comment by BaptisteD** [comment]
Well done ! 
Thanks Scudmarx for the changes. 

Last one, as Adam said it on Discord, could you increase the padding bottom of the header when in scroll mode, to have the same space at the left and bottom of the title ? (1rem) 

Capture d’écran 2021-11-09 à 22 22 49

**Comment by BaptisteD** [comment]
Also, the Upgrade panel seems to be built in a slightly different way. Resulting in a small difference of size. 

Capture d’écran 2021-11-09 à 22 26 30

**Comment by scudmarx** [comment]
> Last one, as Adam said it on Discord, could you increase the padding bottom of the header when in scroll mode, to have the same space at the left and bottom of the title ? (1rem)

OK did this, also made the margins go to -1rem so that the list doesn't snap in a really ugly way when the header's padding changes.

**Comment by scudmarx** [comment]
> Also, the Upgrade panel seems to be built in a slightly different way. Resulting in a small difference of size.

"slightly" 😆 yeah these three identical panels are built in three completely different ways! The header on the upgrades is more variable in size as it will display the less-controllable custom name of the unit. Among other differences. 😄

**Comment by BaptisteD** [comment]
That's perfect for the first two column !! Thank you for that !  :ok_hand:

It seems that the Upgrade panel's header always have the drop shadow, even at the starting position. 
And there is still a difference in size between this one and the two other ones. 
Does it means that it's too hard to have it exactly like the others ? It's not THAT big of a deal but it's a bummer   ^^

**Comment by scudmarx** [comment]
> It seems that the Upgrade panel's header always have the drop shadow, even at the starting position. 

Thought I'd fixed this, but apparently not quite. Think I have now though.

> And there is still a difference in size between this one and the two other ones. Does it means that it's too hard to have it exactly like the others ? It's not THAT big of a deal but it's a bummer ^^

It's an issue that arises from the fact that the Upgrades header has a text input to show user-entered custom unit names which can vary in length. I've brute forced this by telling them to all be a fixed size now; their differing contents are just ignored. This will cause issues if users enter very long custom unit names. Possibly solvable, will take some additional effort.

**Comment by scudmarx** [comment]
Implemented a fix for very long unit names like so:

SoLong

**Comment by BaptisteD** [comment]
Nice, cutting the name is a good idea. 
But where did the edit button and the unit cost go ?

**Comment by scudmarx** [comment]
> ... where did the edit button and the unit cost go ?

They were being pushed off since the name text was taking up as much space as it could. I've now told it to take up only as much as it can without pushing those off, so they are visible again.

**Comment by AdamLay** [comment]
Good stuff - thanks! :)

**Pull request merged**
