### PR TITLE
Data sourcing

### PR DESCRIPTION
**Pull request by scudmarx**
Added some querystring functionality:
- can specify a data source (e.g. "opr-list-builder" or "opr-list-builder-staging" or "opr-list-bui-feature-po-r8wmtp") via querystring: e.g. navigate to "/files?dataSourceUrl=opr-list-builder".
- can specify a game system via querystring, e.g. "/files?gameSystem=gf"
- can specify an army via querystring, e.g. "files?gameSystem=gf&dataSourceUrl=opr-list-builder&armyId=9r82sfzzdmf113c5"

 Made some changes to how Web API data is handled:
- Army files that don't parse properly (there are several on the live webcompanion you may have noticed) will now fail to load elegantly rather than crashing the app.
- ... via some non-breaking refactoring for error handling (data parsing calls have optional failure callbacks)

Let the ArmyImage component find art more intelligently:
- if current system has image, great, use it...
- but if not, check if Army data includes a URL to cover art, and if so fetch it...
- and if not, display the Army Forge logo as a nice fallback default, why not.

### CODE REVIEW

**Comment by scudmarx** [comment]
I see I also accidentally committed some artwork.  Oops.  🤷

**Comment by BaptisteD** [comment]
That's a nice propositions ! 
Could you reduce the size of the Army Forge logo and put it in black plz ?

**Comment by BaptisteD** [comment]
Do you have a screenshot of the error layout when an import failed ?   :)

**Comment by scudmarx** [comment]
> Do you have a screenshot of the error layout when an import failed ? :)
Screenshot 2021-11-06 130533
Error warning snackbar at bottom of window.

**Comment by scudmarx** [comment]
> That's a nice propositions ! Could you reduce the size of the Army Forge logo and put it in black plz ?

Sure, best bet is to have "the art department" 😏 make a nice pretty default logo to use, which could be a smaller blacker AF logo. My own art skills stretch that far if need be.

**Comment by BaptisteD** [comment]
> > Screenshot 2021-11-06 130533

Okay thanks !   :) 
Could you use this color : #ff7043  for the snackbar ?

**Comment by BaptisteD** [comment]
> > That's a nice propositions ! Could you reduce the size of the Army Forge logo and put it in black plz ?
> 
> Sure, best bet is to have "the art department" 😏 make a nice pretty default logo to use, which could be a smaller blacker AF logo. My own art skills stretch that far if need be.

The actual logo is in SVG so you can resize it and change it's color.   :) 
I would aim for a result like this : 

Army selection

**Pull request merged**
