### PR TITLE
Preview units

### PR DESCRIPTION
**Pull request by scudmarx**
Clicking a unit in the UnitSelection list (on desktop view) previews the unit in the Upgrades panel, from where it can be added to your list.

AddToList

This was far more complicated than I was hoping or expecting! 😆

### CODE REVIEW

**Comment by BaptisteD** [comment]
We were thinking about adding this. 
In this case, the user shouldn't be able to change the unit's loadout. 
So for each weapons/upgrades we should hide the buttons and let only the cost. 

For the button, could you rename it "ADD TO MY LIST" and increase the top and bottom margin ?

**Comment by BaptisteD** [comment]
What's the behavior on mobile ?

**Comment by BaptisteD** [comment]
> > ... the user shouldn't be able to change the unit's loadout. So for each weapons/upgrades we should hide the buttons and let only the cost.
> 
> Doesn't this defeat much of the point of previewing a unit?
> 

It's a preview as you say. This unit is not yet in your roaster so it doesn't make sense to customize it yet. 
Are you changing the loadout of this unit in the army list or in yours ? 
As it's the one still in the army list that is selected, it can be really confusing. 
Having it only as a "read only" state makes it crystal clear that you're seeing the options you'll have access to once you've added it !

**Comment by BaptisteD** [comment]
However, you're proposition to have a button can create an interesting workflow. 
You preview the unit by selecting it in the army list. Then you click on the "Add to My List" button, which add it to your list and automatically select it there. 
Therefor, the selection buttons appears, allowing you now to customize it as you please.

**Comment by scudmarx** [comment]
OK all the options in the preview panel are now disabled. 🤷

**Comment by BaptisteD** [comment]
"So for each weapons/upgrades we should hide the buttons and let only the cost."
I didn't say that we should disable them but **hide** them. Of course, it doesn't make sense to show buttons that are unclickable. 
And that they should **appear** once they're added to the user's list.

**Comment by BaptisteD** [comment]
I noticed that only half of the unit card is clickable. The part with the weapons is inactive (it's also the case in the live version of Army Forge). 
Do you know why and would it be possible to make the whole card clickable ?

**Comment by scudmarx** [comment]
> I noticed that only half of the unit card is clickable. The part with the weapons is inactive (it's also the case in the live version of Army Forge). Do you know why and would it be possible to make the whole card clickable ?

> Finally, could you make the same "selected" feedback for units in the army list in the My List ? Capture d’écran 2021-11-24 à 08 29 12

Both done.

**Comment by scudmarx** [comment]
> "So for each weapons/upgrades we should hide the buttons and let only the cost." I didn't say that we should disable them but **hide** them. Of course, it doesn't make sense to show buttons that are unclickable. And that they should **appear** once they're added to the user's list.

This will take a lot more time.

**Comment by BaptisteD** [comment]
Well done ! 
That's exactly that !   :) 
Nice added feature !

**Comment by AdamLay** [comment]
Looking good @scudmarx - if you can resolve the merge conflict I'll close this! Thanks,

**Pull request merged**
